"use server";
import { revalidatePath } from "next/cache";
import { createSupabaseAdminClient, requireAdmin, requireUser } from "@/lib/supabase/server";
import { onlyDigits } from "@/lib/utils/format";
import { propertySchema } from "@/lib/utils/validation";
import type { PropertyFilters } from "@/types/property";
const PAGE_SIZE = 12;
function val(fd: FormData, key: string) { const v = fd.get(key); return typeof v === "string" && v !== "" ? v : undefined; }
function normalize(fd: FormData) { return propertySchema.parse({ name: val(fd,"name"), type: val(fd,"type"), status: val(fd,"status") ?? "ATIVO", price: val(fd,"price"), sold_price: val(fd,"sold_price"), installments_count: val(fd,"installments_count"), first_installment_date: val(fd,"first_installment_date"), owner_name: val(fd,"owner_name"), owner_document: val(fd,"owner_document"), owner_phone: val(fd,"owner_phone"), owner_email: val(fd,"owner_email") ?? "", notes: val(fd,"notes"), zip_code: val(fd,"zip_code"), street: val(fd,"street"), number: val(fd,"number"), complement: val(fd,"complement"), neighborhood: val(fd,"neighborhood"), city: val(fd,"city"), state: val(fd,"state") }); }
export async function getCurrentRole() { try { return (await requireUser()).role ?? null; } catch { return null; } }
export async function getProperties(filters: PropertyFilters = {}) { await requireUser(); const page = Math.max(filters.page ?? 1, 1); const from = (page - 1) * PAGE_SIZE; const admin = createSupabaseAdminClient(); let q = admin.from("properties").select("*", { count: "exact" }).order("created_at", { ascending: false }).range(from, from + PAGE_SIZE - 1); if (filters.search) q = q.or(`name.ilike.%${filters.search}%,owner_name.ilike.%${filters.search}%`); if (filters.status) q = q.eq("status", filters.status); if (filters.type) q = q.eq("type", filters.type); const { data, error, count } = await q; if (error) throw new Error(error.message); return { data: data ?? [], count: count ?? 0, page, pageSize: PAGE_SIZE }; }
export async function getPropertyById(id: string) { await requireUser(); const admin = createSupabaseAdminClient(); const { data, error } = await admin.from("properties").select("*").eq("id", id).single(); if (error) throw new Error(error.message); const [{ data: installments }, { data: contract }] = await Promise.all([admin.from("property_installments").select("*").eq("property_id", id).order("installment_number"), admin.from("property_contracts").select("*").eq("property_id", id).maybeSingle()]); return { ...data, installments: installments ?? [], contract: contract ?? null }; }
export async function createProperty(formData: FormData) { await requireAdmin(); const input = normalize(formData); const admin = createSupabaseAdminClient(); const payload = { ...input, first_installment_date: undefined, owner_document: onlyDigits(input.owner_document), owner_phone: onlyDigits(input.owner_phone), zip_code: onlyDigits(input.zip_code) };
 const { data, error } = await admin.from("properties").insert(payload).select("*").single(); if (error) throw new Error(error.message);
 if (input.status === "VENDIDO" && input.installments_count && input.sold_price && input.first_installment_date) { const amount = Number(input.sold_price) / input.installments_count; const first = new Date(`${input.first_installment_date}T00:00:00Z`); const rows = Array.from({ length: input.installments_count }, (_, i) => { const due = new Date(first); due.setUTCMonth(first.getUTCMonth() + i); return { property_id: data.id, installment_number: i + 1, amount, due_date: due.toISOString().slice(0,10), status: "PENDENTE" }; }); const { error: ie } = await admin.from("property_installments").insert(rows); if (ie) throw new Error(ie.message); }
 revalidatePath("/imoveis"); return data; }
export async function updateProperty(id: string, formData: FormData) { await requireAdmin(); const input = normalize(formData); const { data, error } = await createSupabaseAdminClient().from("properties").update({ ...input, first_installment_date: undefined, owner_document: onlyDigits(input.owner_document), owner_phone: onlyDigits(input.owner_phone), zip_code: onlyDigits(input.zip_code), updated_at: new Date().toISOString() }).eq("id", id).select("*").single(); if (error) throw new Error(error.message); revalidatePath("/imoveis"); revalidatePath(`/imoveis/${id}`); return data; }
