"use server";
import { revalidatePath } from "next/cache";
import { createSupabaseAdminClient, requireAdmin } from "@/lib/supabase/server";
import { onlyDigits } from "@/lib/utils/format";
import { validateUploadFile } from "@/lib/utils/validation";
function ext(file: File) { return file.name.split(".").pop()?.toLowerCase() || (file.type === "application/pdf" ? "pdf" : "jpg"); }
function publicUrl(bucket: string, path: string) { return createSupabaseAdminClient().storage.from(bucket).getPublicUrl(path).data.publicUrl; }
export async function uploadContract(propertyId: string, formData: FormData) { await requireAdmin(); const file = formData.get("file"); if (!(file instanceof File)) throw new Error("Arquivo não enviado"); validateUploadFile(file); const admin = createSupabaseAdminClient(); const { data: property, error: pe } = await admin.from("properties").select("owner_document").eq("id", propertyId).single(); if (pe) throw new Error(pe.message); const path = `${onlyDigits(property.owner_document)}/${crypto.randomUUID()}.${ext(file)}`; const { error } = await admin.storage.from("contratos").upload(path, file, { upsert: true, contentType: file.type }); if (error) throw new Error(error.message); const url = publicUrl("contratos", path); const { error: db } = await admin.from("property_contracts").upsert({ property_id: propertyId, file_url: url, file_type: file.type }, { onConflict: "property_id" }); if (db) throw new Error(db.message); revalidatePath(`/imoveis/${propertyId}`); return { url }; }
export async function uploadInstallmentReceipt(installmentId: string, formData: FormData) { await requireAdmin(); const file = formData.get("file"); if (!(file instanceof File)) throw new Error("Arquivo não enviado"); validateUploadFile(file); const admin = createSupabaseAdminClient(); const { data: inst, error: ie } = await admin.from("property_installments").select("property_id,due_date").eq("id", installmentId).single(); if (ie) throw new Error(ie.message); const path = `${inst.property_id}/${inst.due_date}/${crypto.randomUUID()}.${ext(file)}`; const { error } = await admin.storage.from("comprovantes").upload(path, file, { upsert: true, contentType: file.type }); if (error) throw new Error(error.message); const url = publicUrl("comprovantes", path); const { error: db } = await admin.from("property_installments").update({ comprovante_url: url, status: "PAGO", payment_date: new Date().toISOString().slice(0,10), updated_at: new Date().toISOString() }).eq("id", installmentId); if (db) throw new Error(db.message); revalidatePath(`/imoveis/${inst.property_id}`); return { url }; }
