'use client';
import { useEffect, useState } from 'react';
import { criarImovel, editarImovel, listarImoveis, listarProprietarios } from '@/lib/imoveis-service';
import type { Imovel, ImovelFormData, Proprietario } from '@/types/imoveis';
import { ImovelCard } from '@/components/imoveis/ImovelCard';
import { ImovelDetails } from '@/components/imoveis/ImovelDetails';
import { ImovelFilters, emptyFilters } from '@/components/imoveis/ImovelFilters';
import { ImovelForm } from '@/components/imoveis/ImovelForm';
export default function ImoveisPage(){const[filters,setFilters]=useState(emptyFilters);const[imoveis,setImoveis]=useState<Imovel[]>([]);const[props,setProps]=useState<Proprietario[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');const[selected,setSelected]=useState<Imovel>();const[editing,setEditing]=useState<Imovel|undefined>();const[creating,setCreating]=useState(false);async function load(){setLoading(true);setError('');try{const[p,i]=await Promise.all([listarProprietarios(),listarImoveis(filters)]);setProps(p);setImoveis(i)}catch(e){setError(e instanceof Error?e.message:'Erro ao carregar imóveis.')}finally{setLoading(false)}}useEffect(()=>{load()},[filters]);async function save(data:ImovelFormData){if(editing) await editarImovel(editing.id,data); else await criarImovel(data);setCreating(false);setEditing(undefined);await load()}return <section><div className="toolbar"><div><h2>Imóveis</h2><p className="muted">Gestão completa de imóveis, proprietários e faturas vinculadas.</p></div><button onClick={()=>setCreating(true)}>Novo Imóvel</button></div><ImovelFilters filters={filters} onChange={setFilters} onClear={()=>setFilters(emptyFilters)} />{(creating||editing)&&<ImovelForm imovel={editing} proprietarios={props} onCancel={()=>{setCreating(false);setEditing(undefined)}} onSubmit={save} />}{loading&&<div className="panel">Carregando imóveis...</div>}{error&&<div className="panel danger">{error}</div>}{!loading&&!error&&imoveis.length===0&&<div className="panel">Nenhum imóvel encontrado. Cadastre um novo imóvel ou ajuste os filtros.</div>}<div className="grid">{imoveis.map(i=><ImovelCard key={i.id} imovel={i} onClick={()=>setSelected(i)} />)}</div>{selected&&<ImovelDetails imovel={selected} onClose={()=>setSelected(undefined)} onEdit={()=>{setEditing(selected);setSelected(undefined)}} />}</section>}
