<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>VoltPy.Service</AssemblyName>
    <RootNamespace>VoltPy.Service</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\VoltPy.Loader\VoltPy.Loader.csproj" />
  </ItemGroup>
</Project>
