spring.application.name=hub-erp
spring.profiles.active=dev
spring.datasource.url=jdbc:h2:mem:huberp;DB_CLOSE_DELAY=-1
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.thymeleaf.cache=false

logging.file.name=logs/hub-erp.log
logging.level.root=INFO
logging.level.com.example.demo=DEBUG

app.upload.dir=uploads
app.external-api.mock-enabled=true
