import { useState, type FormEvent } from 'react';
import type { Imovel, ImovelFormData, Proprietario } from '@/types/imoveis';
const initial: ImovelFormData = { proprietario_id:'', codigo:'', nome:'', tipo:'', cep:'', endereco:'', numero:'', complemento:'', bairro:'', cidade:'', estado:'', area_total:null, area_construida:null, matricula:'', cartorio:'', valor_venda:null, valor_aluguel:null, situacao:'ativo', observacoes:'' };
export function ImovelForm({ imovel, proprietarios, onCancel, onSubmit }: { imovel?: Imovel; proprietarios: Proprietario[]; onCancel: () => void; onSubmit: (d: ImovelFormData) => Promise<void> }) {
  const [data,setData]=useState<ImovelFormData>(imovel?{...initial,...imovel}:initial); const [saving,setSaving]=useState(false); const [error,setError]=useState('');
  const set=(k:keyof ImovelFormData,v:string)=>setData({...data,[k]:['area_total','area_construida','valor_venda','valor_aluguel'].includes(k)?(v===''?null:Number(v)):v});
  async function submit(e: FormEvent){e.preventDefault(); setError(''); if(!data.proprietario_id) return setError('Selecione um proprietário.'); if(!data.codigo||!data.nome) return setError('Código e nome são obrigatórios.'); setSaving(true); try{await onSubmit(data)}catch(err){setError(err instanceof Error?err.message:'Erro ao salvar imóvel.')}finally{setSaving(false)}}
  const fields:(keyof ImovelFormData)[]=['codigo','nome','tipo','cep','endereco','numero','complemento','bairro','cidade','estado','area_total','area_construida','matricula','cartorio','valor_venda','valor_aluguel','situacao','observacoes'];
  return <form className="form" onSubmit={submit}><h3>{imovel?'Editar imóvel':'Novo imóvel'}</h3>{error&&<p className="danger">{error}</p>}<label>Proprietário<select value={data.proprietario_id} onChange={e=>set('proprietario_id',e.target.value)}><option value="">Selecione</option>{proprietarios.map(p=><option key={p.id} value={p.id}>{p.nome ?? p.id}</option>)}</select></label>{fields.map(k=><label key={k}>{k}{k==='observacoes'?<textarea value={String(data[k]??'')} onChange={e=>set(k,e.target.value)} />:<input type={['area_total','area_construida','valor_venda','valor_aluguel'].includes(k)?'number':'text'} value={String(data[k]??'')} onChange={e=>set(k,e.target.value)} />}</label>)}<button disabled={saving}>{saving?'Salvando...':'Salvar imóvel'}</button><button type="button" className="secondary" onClick={onCancel}>Cancelar</button></form>;
}
